version: '3'
services:
  comm:
    build:
      dockerfile: Dockerfile
      context: ./build
    working_dir: /var/www/html
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/server.conf:/etc/nginx/conf.d/server.conf
      - ./php-fpm/conf/php.ini:/etc/php.ini
      - ./php-fpm/conf/www.conf:/etc/php-fpm.d/www.conf
      - ./supervisord/supervisord.conf:/etc/supervisord.conf
      - ./src/project:/var/www/html
    ports:
      - 12080:80
